### ISSUE TITLE
Information about this package

### ISSUE THREAD

**Issue by ReynerHL** [DUBroquin/Vuetable#1]
Well, this is just a question, hope you can answer it. In the readme, you wrote:

> This package is a fork of _yajra/laravel-**vuetables**_ created by Arjay Angeles

Can you please provide the link to that repo? I would like to combine "yajra/laravel-datatables" backend logic with "ratiw/vuetable-2" component in client side.

Thanks in advance.

**Comment by dubroquin** [comment]
Hello, sorry for the readme, I cleaned it.

The package *yajra/laravel-vuetables* doesn't exist, but this package is designed to use yajra/laravel-datatables logic for Vuetable.
